// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlGOjP-WMQI4rIJN2V8L3nQFgQHdFxFLw',
    appId: '1:11952084698:web:61d5410d20d594376eb7e3',
    messagingSenderId: '11952084698',
    projectId: 'e-learning-information',
    authDomain: 'e-learning-information.firebaseapp.com',
    storageBucket: 'e-learning-information.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC29Mrbu1dGPHrmYrDSxHEEX9HoRGYjWCk',
    appId: '1:11952084698:android:e44ed8f9bc3fef356eb7e3',
    messagingSenderId: '11952084698',
    projectId: 'e-learning-information',
    storageBucket: 'e-learning-information.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlu4VxoDDwCsvtBgeFhIo84vOY5nopOK0',
    appId: '1:11952084698:ios:db45e239fa0063a06eb7e3',
    messagingSenderId: '11952084698',
    projectId: 'e-learning-information',
    storageBucket: 'e-learning-information.firebasestorage.app',
    iosBundleId: 'com.example.eLearningPlatformKoala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlu4VxoDDwCsvtBgeFhIo84vOY5nopOK0',
    appId: '1:11952084698:ios:db45e239fa0063a06eb7e3',
    messagingSenderId: '11952084698',
    projectId: 'e-learning-information',
    storageBucket: 'e-learning-information.firebasestorage.app',
    iosBundleId: 'com.example.eLearningPlatformKoala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlGOjP-WMQI4rIJN2V8L3nQFgQHdFxFLw',
    appId: '1:11952084698:web:9d2c9dcd8e7b23736eb7e3',
    messagingSenderId: '11952084698',
    projectId: 'e-learning-information',
    authDomain: 'e-learning-information.firebaseapp.com',
    storageBucket: 'e-learning-information.firebasestorage.app',
  );

}